package ua.com.javajedi.model.statistics;

public enum Action {
	GET_INDEX,
	LOGIN,
	ADD_COMMENT,
	READ_ARTICLE,
	GET_ARTICLES_ALL,
	GET_ARTICLES_UNREAD,
	GET_EXERCISES_ALL,
	GET_EXERCISES_UNDONE,
	TRY_EXERCISE,
	SUCCESS_EXERCISE,
	FAIL_EXERCISE
}
