INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('2', false, 1);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('4', false, 1);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('8', true, 1);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('12', false, 1);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Примитивы и ссылочные типы', TRUE , 2);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('int, char, String и им подобные', false, 2);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Long, Double, Byte и ссылочные типы', false, 2);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Ссылки и адреса в памяти', false, 2);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Буквы, цифры и строки', false, 2);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Раннее', false, 3);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Позднее', TRUE , 3);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Среднее', false, 3);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Что это?', false, 3);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Мягкая типизация', false, 4);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Строгая типизация', TRUE , 4);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Легкая типизация', false, 4);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Поздняя типизация', false, 4);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Примитив', false, 5);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Позитив', false, 5);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Ссылочный', TRUE , 5);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('Капитальный', false, 5);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('0', false, 6);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('1', false, 6);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('3', false, 6);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('2', TRUE , 6);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('В операционной системе', false , 7);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('В куче', false , 7);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('В стеке потока', TRUE , 7);
INSERT INTO java_jedi_secured.answer (content, is_correct, exercise_id) VALUES ('В виртуальной машине Java', false , 7);